{% set name = "altdphi" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 941619105c2ae9421cee5a149aee50d4615637b92daec8a64c3362b5dba17e71

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - altdphi

about:
  home: https://github.com/TaiSakuma/altdphi
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'An alternative variables for new physics searches at LHC'
  description: |
    A library for calculating alternative variables for background
    rejection in new physics searches with missing transverse momentum
    at LHC.
  dev_url: https://github.com/TaiSakuma/altdphi
  doc_url: https://altdphi.readthedocs.io

extra:
  recipe-maintainers:
    - TaiSakuma
