travis:
  secure:
    BINSTAR_TOKEN: HfeR/71HGUC3GHa2XrHoJDA6q12frVq9UBhL9d/UPsi6zRk9iB7C+tx6kIbEFpWiu4N1yRO6nTd6BmSUhdwjyCq4mlQuELJtEAxDj+N1reaHuaHtkjSRriHn0PrqkqXsfsh6yKEss7zXfdQQv4lRsRcTUd1WAZj1pLttDso+JLNElFEmMJZkQEa/2JMctoQTZObMRDhBuKDSznLAd/u9FuAnWu4Lr3A8hYHkl6+U4Q5TDFyLqwBuTvHVHIA6LzRuijdyiVmlrrhX6XLIitl3qf4VQYEGogw+3PEqClDVLA/zLGu+TRBOwiD7lq3N+2Pnu/0+nyKVM8+qy/jz4r6sEej91KwSTd/bF9gZnaTV8f/07ZDJ2XJ4v71wGRESHo2knTNatXj2debzlmwXr+5vTXr1eXKDKu/C3IBX4LPo72jnpfpvzDgc4ddMJhfphUb1RTVJJwhDSoD9yFwHbBenjjVIRW/rPraaT25nGbJSucud5NFiA1KYdRQeRVAJ/4bOS0Kq0XJ1ek71fRzyTAYVhFdb2acDWEME16E7f0/98BRfe8F/YbVcmH2lrVO22PRtQlOwoKBTQrw+U40M2gIszt8j5IlsRmIXEeGYI0r0Rnb6yFnB+CZgnZQYPMi+Hw3zQMnVl3+5pYUHiEHREqrY7TWjStuer4YfZ9jsP3pMcXs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
